---
title: "compileData()"
author: "ATfiltR Team"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
vignette: >
  %\VignetteIndexEntry{2. compileData()}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

OK, you should have a project openned in R, and your detections should be stored in a sub-folder of the project. 

If that's not the case, [**Go back here**](Getting_started_with_ATFiltR.html)


## compileData()

The function `compileData()` will make your long list of temetry data files into one single `.RData` file, which can be used in the rest of the package.

The function will also identify the columns of your files. We did this because all telemetry systems may organize their data slightly differently and we wanted `ATfiltR` to be useable as broadly as possible. So, there is going to be a little dialogue between you and the programm, in order to identify the different columns.

<br />
<br />  

### General arguments  

```{r, eval=F}
compileData(detection.folder="Detections", file.ext=".csv",
            sep.type=",", save=TRUE, remove.duplicates=T, 
            save.duplicates=F, split=T)
```

**detection.folder**  
<hr />

You should have an R project, and within the project directory you should have a folder that contains all of your telemetry data files. Indicate the name of the folder in quotation marks. By default we indicated "Detections".

**file.ext**  
<hr />

Indicate what the extension of your data files is. This is usually `.csv` but your files can also be in other "value separated" format like `.txt`. ATfiltR will ignore all files that are stored in the `detection.folder` but don't have the indicated `file.ext`. By default we indicated ".csv".


**sep.type**  
<hr />

What character separates the columns in your data files. By default we indicated ",".

**save**  
<hr />

Would you like to save the data compiled by `ATfiltR`. Default is `TRUE`.

**remove.duplicates**  
<hr />

Would you like `ATfiltR` to identify and remove duplicated detections (same tag ID, same receiver ID, same Timestamp). Default is `TRUE`.


**save.duplicates**  
<hr />

Would you like `ATfiltR` to save the removed duplicates as a data.frame is your `detection.folder`. Default is `TRUE`.


**split**  
<hr />

Should `ATfiltR` compile your data little by little, in batches. This is recommended especially if you have a LOT of data. It will prevent R from crashing due to memory issues. Default is `TRUE`.


<br />
<br />  

### Sneak peek into running the function  

Once the arguments are all set, you will run the function. This function requires some input from you. We purposefully made it interactive to make it usable across data formats. 
You will need to identify the *Timestamp*, *Transmitter ID*, *Receiver ID* columns for instance. 
`ATfiltR` will ask you questions, which you can answer in the console. Here are a few example screenshots.

